### PR TITLE
Use git instead of svn

### LINKED ISSUE #1: Doesn't work with git
Current implementation is still written against SVN. It should be updated to use git repositories for building the installer.

### PR DESCRIPTION
**Pull request by keremispirli**
Implemented generating installer by using git repositories

!!! Banner & dialog bmp's are not provided yet, so they're missing !!!
!!! Npp plugin is not included in .msi yet !!!

- Ignore tag folder
- Remove and ignore user files (ide files, out folder)
- Remove and ignore WxsGenerator.jar
- Add buildWxsGenerator.bat to generate WxsGenerator.jar locally
- Add buildinfo.bat

TxsCreateInstaller.bat:
- Intentionally use results of previous builds
- Add NOCACHE parameter (1/0) to force building everything from scratch
- Checkout SupportEclipse and SupportNpp plugins from their respective
 git repositories
- Fix generating version info file
- Remove "stack clean" to prevent unnecessary rebuilding of TorXakis
- Inline build.bat
- Build WxsGenerator.jar if it's absent
- Copy all necessary files into <tag>\WindowsInstaller folder and
 build installer from there
- Fix Wxs compilation and linking

WxsGenerator:
- Change WxsGenerator implementation for current structure with git
 and tags
- Add META-INF in order to be able to build the jar
- Ensure WindowsInstaller folder exists and work from it
- Copy EditorPlugins locally
- Variable name improvements
- Add KeyPath attribute to Component1 while generating wxs to fix
 warning from light.exe
- Build datestamp (yyyyMMdd) locally instead of extracting from
 (SVN) tag

Closes #1

### CODE REVIEW

**Comment by keremispirli** [comment]
Created #4  for NPP plugin

**Review by pjljvandelaar — COMMENTED** [review]
Why are .stack-work and stack.yaml part of .gitignore file?
TorXakis is build in TorXakis/ which is already in ignore!

**Comment by keremispirli** [comment]
they are from the time I was trying to stack build in wrong directory... I forgot them in!

Gonna fix now

**Comment by pjljvandelaar** [comment]
About: •Add NOCACHE parameter (1/0) to force building everything from scratch

Is this a good idea?
Should a release not be build from scratch always to maximize the change of reproducibility?
Sometimes things go wrong or ok due to the files in the cache.
For a release, we definitely don't want that... we want to be able to rebuild the same release!

**Comment by keremispirli** [comment]
NOCACHE option is primarily for saving time during development of this tool.
Building the installer is always done from scratch but downloading same repositories (TorXakis, Npp and Eclipse plugins), rebuilding TorXakis with stack and rebuilding WxsGenerator over and over again result in exact same outputs every time; so they can be skipped after being done once. When we have automated builds with CI, it will always do everything from scratch anyway.

Changing default value to 1 is an option, but I think forgetting to tell the script to use cache and losing time because now everything has to be rebuilt is more of a problem than intentionally forcing the script to start from scratch when necessary.

**Comment by keremispirli** [comment]
Another thing about NOCACHE: Since all the dependencies are still checked at every step, if one of them fails then we can just delete that one and it will be rebuilt while other successfully built dependencies are reused.

E.g. Let's say I'm working on WxsGenerator. I run the script but my changes aren't good yet, so I can just delete WxsGenerator.jar file and when I run the script it will be rebuilt, while TorXakis repository will not be re-downloaded or rebuilt with stack.

**Review by pjljvandelaar — APPROVED** [review]

**Pull request merged**
